In [1]:
import os

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '100 smallgray.png',
 '102 smallgray.png',
 'Untitled.ipynb']

In [3]:
import numpy

In [4]:
import cv2

In [10]:
image = cv2.imread("100 smallgray.png", 1
                  )

In [11]:
print(image)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [15]:
image2 = cv2.imwrite("newsmallgrey1.png", image)

In [16]:
print(image2)

True


In [17]:
os.listdir()

['.ipynb_checkpoints',
 '100 smallgray.png',
 '102 smallgray.png',
 'newsmallgrey1.png',
 'Untitled.ipynb']